### ISSUE TITLE
Expose exp1m in python API

### ISSUE THREAD

**Issue by vpipkt** [s22s/rasterframes#24]

**Comment by vpipkt** [comment]
QA procedure will be same as described here: https://github.com/s22s/astraea-earth-platform/issues/244#issuecomment-475668752 

Runs relatively quickly on a medium size cluster.

**Comment by courtney-whalen** [comment]
I am still getting this error on test environment. See error message below.

Execution exception:

Traceback (most recent call last):
  File "/tmp/1555432958427-0/pyexecutor/code_executor.py", line 53, in _supervised_execution
    self._run_custom_code(workflow_id, node_id, custom_operation_code)
  File "/tmp/1555432958427-0/pyexecutor/code_executor.py", line 115, in _run_custom_code
    output_data = context[self.TRANSFORM_FUNCTION_NAME](input_data_frame)
  File "<string>", line 18, in transform
AttributeError: 'module' object has no attribute 'exp1m'

**Comment by vpipkt** [comment]
Did you import pyrasterframes.rasterfunctions?

**Comment by courtney-whalen** [comment]
Yeah, I used the workflow you provided here: s22s/astraea-earth-platform#244. It has `from pyrasterframes import rasterfunctions as RF` at the top
