### ISSUE TITLE
Python `head`, `take` and `collect` throw with Tile column

### ISSUE THREAD

**Issue by vpipkt** [s22s/rasterframes#7]
Use case: user calls `head`, `take` and `collect` on dataframe with a Tile column in it.

Expected result: Not sure. numpy array for tiles?  Abstract toString kind of representation like `'RasterRefTile(RasterRef(S3GeoTiffRasterSource(s3://s22s-demeter-data-assets-prod/MCD43A4.006/18/07/2012265/MCD43A4.A2012265.h18v07.006.2016109213623_B01.TIF),Some(Extent(222390.1039334, 1223145.5716336002, 333585.1559001, 1334340.6236002))))'`

Actual result:

```
Py4JJavaErrorTraceback (most recent call last)
<ipython-input-55-eb69687bcc7c> in <module>()
----> 1 e = df.where(F.col('siteid') == '100103514499')     .select(['siteid', 'extent', 'id', 'B01'])     .limit(2).collect()
      2     #.head(2)

/opt/spark-2.3.2/python/pyspark/sql/dataframe.pyc in collect(self)
    465         with SCCallSiteSync(self._sc) as css:
    466             sock_info = self._jdf.collectToPython()
--> 467         return list(_load_from_socket(sock_info, BatchedSerializer(PickleSerializer())))
    468 
    469     @ignore_unicode_prefix

/opt/spark-2.3.2/python/pyspark/serializers.pyc in load_stream(self, stream)
    144         while True:
    145             try:
--> 146                 yield self._read_with_length(stream)
    147             except EOFError:
    148                 return

/opt/spark-2.3.2/python/pyspark/serializers.pyc in _read_with_length(self, stream)
    169         if len(obj) < length:
    170             raise EOFError
--> 171         return self.loads(obj)
    172 
    173     def dumps(self, obj):

/opt/spark-2.3.2/python/pyspark/serializers.pyc in loads(self, obj, encoding)
    567     else:
    568         def loads(self, obj, encoding=None):
--> 569             return pickle.loads(obj)
    570 
    571 

/opt/spark-2.3.2/python/pyspark/sql/types.pyc in <lambda>(*a)
   1426 # This is used to unpickle a Row from JVM
   1427 def _create_row_inbound_converter(dataType):
-> 1428     return lambda *a: dataType.fromInternal(a)
   1429 
   1430 

/opt/spark-2.3.2/python/pyspark/sql/types.pyc in fromInternal(self, obj)
    628             # Only calling fromInternal function for fields that need conversion
    629             values = [f.fromInternal(v) if c else v
--> 630                       for f, v, c in zip(self.fields, obj, self._needConversion)]
    631         else:
    632             values = obj

/opt/spark-2.3.2/python/pyspark/sql/types.pyc in fromInternal(self, obj)
    440 
    441     def fromInternal(self, obj):
--> 442         return self.dataType.fromInternal(obj)
    443 
    444     def typeName(self):

/opt/spark-2.3.2/python/pyspark/sql/types.pyc in fromInternal(self, obj)
    685         v = self._cachedSqlType().fromInternal(obj)
    686         if v is not None:
--> 687             return self.deserialize(v)
    688 
    689     def serialize(self, obj):

/tmp/spark-af2daaf1-0696-4d94-a0d0-81080f88d32f/userFiles-3ab2f85d-50c9-4c11-a8fe-df8dcacf1c78/pyrasterframes_2.11-0.8.0-RC2-python.zip/pyrasterframes/types.py in deserialize(self, datum)
    169 
    170     def deserialize(self, datum):
--> 171         return RFContext._jvm_mirror().generateTile(datum[0], datum[1], datum[2], datum[3])
    172 
    173 

/tmp/1549556585804-0/py4j/java_gateway.pyc in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/spark-2.3.2/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/tmp/1549556585804-0/py4j/protocol.pyc in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o474.generateTile.
: java.lang.NullPointerException
	at geotrellis.raster.ShortArrayTile$.constructShortArray(ShortArrayTile.scala:338)
	at geotrellis.raster.ShortArrayTile$.fromBytes(ShortArrayTile.scala:373)
	at geotrellis.raster.ArrayTile$.fromBytes(ArrayTile.scala:453)
	at astraea.spark.rasterframes.py.PyRFContext.generateTile(PyRFContext.scala:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vpipkt** [comment]
My bad here for not capturing the workflow that generated this error. I now have the attached, which instead gives a `None` for any kind of collect into the python driver. Does not throw an error on the Java side. 

[RF_7.json.txt](https://github.com/s22s/rasterframes/files/3031196/RF_7.json.txt)

**Comment by vpipkt** [comment]
I am going to close this and instead create a new issue with enhancement tag.
